### ISSUE TITLE
emacs-compatible .skhdrc bindings?

### ISSUE THREAD

**Issue by hummuscience** [ianpan870102/.personal-emacs.d#1]
I saw that you use yabai + emacs and figured I could ask about which keybindings work best for you as alt is heavily used in emacs and the standard skhd keybindings for yabai are all based on alt.

**Comment by ianyepan** [comment]
Glad you brought this up. I'm actually using vi-bindings in Emacs (i.e. evil-mode), so I don't make use of alt in emacs that often.

**Comment by ianyepan** [comment]
Hope this solved your question, feel free to reopen if there's more to ask.
